# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamiward', '0002_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=70),
        ),
    ]
