# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-05 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kamiward', '0004_auto_20190905_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='editor',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
