# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamiward', '0006_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kamiward.Profile'),
        ),
    ]
